name: "Generate Release Tag Action"
description: "Creates custom tag based on Pull Request Labels"
inputs:
  github_token:
    description: "Github token to use for octokit requests"
    required: true
  prefix:
    description: "Tag prefix to use."
    required: false
outputs:
  new_tag:
    description: "Tag generated"
runs:
  using: "node12"
  main: "dist/index.js"
