name: Release

on:
  push:
    branches: [main]

env:
  should_run: false

jobs:
  build-generate-release-tag-action:
    runs-on: ubuntu-latest
    if: should_run
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        working-directory: generate-release-tag-action
        run: npm ci

      - name: Run tests, build and package dist.
        working-directory: generate-release-tag-action
        run: |
          npm run all

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "New build of generate-release-tag-action"
          commit_user_name: Henrik Knudsen
          commit_user_email: henrik.knudsen@bouvet.no
          commit_author: Henrik Knudsen <henrik.knudsen@bouvet.no>
