name: Release

on:
  push:
    branches: [main]

jobs:
  build-generate-release-tag-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        working-directory: generate-release-tag-action
        run: npm ci

      - name: Run tests, build and package dist.
        working-directory: generate-release-tag-action
        run: |
          npm run all

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "New build of generate-release-tag-action"
          commit_user_name: Henrik Knudsen
          commit_user_email: henrik.knudsen@bouvet.no
          commit_author: Henrik Knudsen <henrik.knudsen@bouvet.no>

  create-release:
    needs: [build-generate-release-tag-action]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - run: ls

      - name: Bump version and push tag
        id: tag_version
        uses: ./generate-release-tag-action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          prefix: "v"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          name: Release  ${{ steps.tag_version.outputs.new_tag }}
          generate_release_notes: true

      - name: Check Output Parameters
        run: |
          echo "Tag: ${{ steps.release.outputs.new_tag }}"
          echo "Version: ${{ steps.release.outputs.new_version }}"

