name: Release

on:
  push:
    branches: [main]

jobs:
  build-generate-release-tag-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run tests, build and package dist.
        working-directory: generate-release-tag-action
        run: |
          npm run all

  create-release:
    needs: [build-generate-release-tag-action]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Bump version and push tag
        id: tag_version
        uses: mimir-org/mimir-actions/generate-release-tag-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          prefix: "v"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          name: Release  ${{ steps.tag_version.outputs.new_tag }}
          generate_release_notes: true

      - name: Check Output Parameters
        run: |
          echo "Tag: ${{ steps.release.outputs.new_tag }}"
          echo "Version: ${{ steps.release.outputs.new_version }}"

